# conda env create -f environment.yaml
name: simple_streamlit
channels:
 - defaults
dependencies:
 - jupyter=1.0.0
 - pandas=1.5.1
 - matplotlib=3.5.3
 - scipy=1.9.3
 - python=3.10.8
 - pip=22.2.2
 - scikit-learn=1.1.3
 - joblib=1.1.1
 - streamlit=1.11.0
